# Generated by Django 5.1.4 on 2024-12-17 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_author_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.author'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.category'),
        ),
        migrations.AlterField(
            model_name='author',
            name='edad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
