# Generated by Django 5.1.4 on 2024-12-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_author_task_category_alter_author_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategoria',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
